apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: echo-server
    app.kubernetes.io/name: echo-server
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: echo-server
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: echo-server
        app.kubernetes.io/name: echo-server
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/haoshuwei24/echo-server:v1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: echo-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
