apiVersion: game.kruise.io/v1alpha1
kind: GameServerSet
metadata:
  name: minecraft
spec:
  replicas: {{ .Values.replicas }}
  gameServerTemplate:
    spec:
      containers:
        - image: "{{ .Values.image }}"
          name: minecraft
          env:
            - name: aliyun_logs_minecraft
              value: stdout
        - image: "{{ .Values.sidecarImage }}"
          name: sidecar
  updateStrategy:
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      maxUnavailable: 100%