{{- if .Values.scaled.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: minecraft
spec:
  scaleTargetRef:
    name: minecraft
    apiVersion: game.kruise.io/v1alpha1
    kind: GameServerSet
  pollingInterval: 30
  minReplicaCount: 0
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 5
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
  triggers:
    - type: external
      metricType: AverageValue
      metadata:
        minAvailable: "3"
        scalerAddress: kruise-game-external-scaler.kruise-game-system:6000
{{- end }}