apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: echo-server-2
    app.kubernetes.io/name: echo-server-2
  name: echo-server-2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: echo-server-2
    app.kubernetes.io/name: echo-server-2
  type: ClusterIP
