apiVersion: policy.one.alibabacloud.com/v1alpha1
kind: OverridePolicy
metadata:
  name: echo-server-op
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: echo-server
  overrideRules:
    - overriders:
        plaintext:
          - operator: add
            path: /metadata/labels/a
            value: a1
#      targetCluster:
#        clusterNames:
#          - clusterid