
registryDomain: registry-cn-hongkong.ack.aliyuncs.com
image: acs/web-demo
tag: v0.6.0-2

replicas: 1

envCluster: cluster-oneregion
envSvcName: service1
envCallSvcName: ""
envSvcPort: 80
## svc or call
envAPI: svc

clusterId: ""

isNodePort: false

onlyService: false

global:
  nodeSelector: {}

  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
