apiVersion: v1       
kind: Service
metadata:
  name: service1
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: web-demo
  {{ if .Values.isNodePort }}
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30100
  {{ else }}
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  {{ end }}
  sessionAffinity: None