apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  template:
    spec:
      containers:
      - image: demo-test-registry.cn-hangzhou.cr.aliyuncs.com/cidemo/echo-server:v2.0
        name: echo-server
