apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    run: grpc-service
  sessionAffinity: None
  type: NodePort