apiVersion: v1
kind: Pod
metadata:
  name: curl-client
spec:
  containers:
    - name: curl-client
      image: registry-cn-hangzhou.ack.aliyuncs.com/dev/curl:8.11.1
      command: ["sh", "-c", "sleep 12000"]