helm:
  parameters:
  - name: image.echoServer.repository
    value: demo-test-registry.cn-hangzhou.cr.aliyuncs.com/cidemo/echo-server
    forcestring: true
  - name: image.echoServer.tag
    value: v2.1
    forcestring: true
  - name: image.echoWebServer.repository
    value: demo-test-registry.cn-hangzhou.cr.aliyuncs.com/cidemo/echo-web-server
    forcestring: true
  - name: image.echoWebServer.tag
    value: v1.0
    forcestring: true
