{{- if .Values.secretManager.enabled }}
apiVersion: alibabacloud.com/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretManager.secretName }}
spec:
  data:
    - key: {{ .Values.secretManager.kmsKey }}
      name: {{ .Values.secretManager.dataName }}
      versionStage: {{ .Values.secretManager.versionStage }}
{{- end }}