{{- if .Values.rollout.enabled -}}
apiVersion: rollouts.kruise.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  annotations:
    rollouts.kruise.io/rolling-style: partition
spec:
  objectRef:
    workloadRef:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ include "echo-server.fullname" . }}
  strategy:
    canary:
      steps:
        - replicas: 20%
          weight: 20
        - replicas: 40%
          weight: 40
          pause:
            duration: 60
        - replicas: 60%
          weight: 60
          pause:
            duration: 60
        - replicas: 80%
          weight: 80
          pause:
            duration: 60
      trafficRoutings:
        - service: {{ include "echo-server.fullname" . }}
          ingress:
            classType: nginx
            name: {{ include "echo-server.fullname" . }}
{{- end }}